### ISSUE TITLE
Set head follow or position of standard notification fails

### ISSUE THREAD

**Issue by ThreepE0** [BOLL7708/OpenVRNotificationPipe#6]
Hello, is it possible to set a "standard" notification's position at all?  I can only get the custom notifications positioned how I'm looking for.  

It doesn't appear that the custom notifications support entering text either, is that correct?

Trying to determine if I should work on generating the PNGs on the fly and sending those, or should I just use the standard notifications.

Thanks for your work on this so far.  Any help or advice would be greatly appreciated.

**Comment by BOLL7708** [comment]
Oh yeah the standard notification is entirely driven by SteamVR, we cannot affect the positioning or appearance of it, sadly 😟

The custom notifications do have text support, you can add multiple text fields with font settings, size, position, etc. It should be available in the included editor.

Personally I've made an image generator for Twitch chat messages, it's not perfect, but mostly works, it's available in [streaming_widget](https://github.com/BOLL7708/streaming_widget/blob/ed678a4c06614bf1d049908bd528ae418009c9cf/src/Classes/ImageEditor.ts). I never polished it up though so it's overly complex for what it is 😅 

Closing this as the issue itself cannot be fixed!

**Comment by ThreepE0** [comment]
> The custom notifications do have text support, you can add multiple text fields with font settings, size, position, etc. It should be available in the included editor.
![image](https://user-images.githubusercontent.com/3989824/205453076-62f01fee-1787-4e75-b3e5-5368edfb576a.png)
![image](https://user-images.githubusercontent.com/3989824/205453282-af9ca6d8-1824-4289-bd18-57b5ec5e0720.png)

Thank you so much for the reply!  I'd like to send you a few bucks as a thank you if that's ok, do you have a donation link?

Please bear with me as I could very well be just missing something simple, but in the included example, I don't see any spots for font size, or to customize the text in a custom message.  The text bubble always says "This is a test message" for example, no matter what I have in the "Message" form field.

Noticing that when sending a custom notification, my custom text does get sent, but the image with the stock text is all that's shown. 

I've attached a couple of screenshots of what I'm looking at if that helps.
